export const myresume = {
  me: {
    name: "امید سهیل‌نیا",
    job: "Front-End web developer",
    phone: "+ 98 935 440 3007",
    address: "Iran, Tehran(west)",
    age: 1372,
    relationship: "Single",
    intrests: ["Online Game", "Music", "Study", "Tourism"],
    email: "soheilniao@gmail.com",
  },
  languages: [
    { language: "English", level: 75 },
  ],
  skills: [
    { tool: "Html, CSS, CSS3, SASS", level: 80 },
    { tool: "BootStrap, Styled-component, Ant-Design, Material-UI", level: 80 },
    { tool: "JavaScript ES6", level: 75 },
    { tool: "ReactJS", level: 80 },
    { tool: "NextJS", level: 70 },
    { tool: "React-Native", level: 40 },
    { tool: "TypeScript", level: 60 },
    { tool: "Redux", level: 75 },
    { tool: "Api, axios, Postman", level: 75 },
    { tool: "NodeJS, ExpressJS", level: 65 },
    { tool: "MongoDB, Prisma", level: 75 },
    { tool: "GraphQL", level: 30 },
    { tool: "Git", level: 80 },
    { tool: "CorelDraw", level: 40 },
  ],
  education: {
    degree: "کارشناسی فناوری اطلاعات",
    startAt: 1391,
    endAt: 1395,
    location: "دانشگاه آزاد اسلامی واحد پرند",
  },
  work_experiences: [
    {
      name: "شرکت نرم افزاری سپیدار",
      location: "تهران",
      description: ['html, css', 'JavaScript', 'reactJS'],
    },
    {
      name: "شرکت انتقال داده‌های آسیاتک",
      location: "تهران",
      description: ['b2b', 'front-end for b2c'],
    },
    {
      name: "فروشگاه پلازیو",
      location: "تهران",
      description: ['reactJS', 'react-native'],
    },
  ],
  self_projects: [
    {
      projectName: "Online Shope",
      description: "در این پروژه امکان مشاهده محصولات، ثبت و خرید می باشد. توسط دسترسی ادمین سفارشات مدیریت و ثبت میشوند. دسترسی ادمین جهت مشاهده نمونه کار در دسترس عموم قرار گرفته است.",
      description2:'در صورتی که پروژه به صورت انلاین آپ نشد، لطفا با فیلترشکن باز نمایید.',
      description3: '',
      tools: ['NextJS', 'MongoDB', 'Redux', 'CSS', 'BootStrap'],
      links: { github: "https://github.com/omids0/nextjs-online-shop", live: "https://omid-shop.vercel.app/" },
    },
    {
      projectName: "Staff Resturant Menu",
      description: "این پروژه جهت استفاده کارکنان داخل رستوران طراحی شده است. از ظاهر جالبی برخوردار نیست، اما شرایط کار را آسان تر کرده است. سطح دسترسی ها در این پروژه لحاظ شده است.",
      description2:'در صورتی که پروژه به صورت انلاین آپ نشد، لطفا با فیلترشکن باز نمایید.',
      description3: 'username:10001;   password:admin',
      tools: ['ReactJS', 'CSS', "BootStrap", "ExpressJS", "Redux", "MongoDB"],
      links: { github: "https://github.com/omids0/staff-menu", live: "https://staff-menu-omid.vercel.app/" },
    },
    {
      projectName: "A set of JavaScript and React training projects",
      description: "مجموعه ای از پروژه های تمرینی و تفریحی که توسط اینجانب انجام شده است.",
      description2:'در صورتی که پروژه به صورت انلاین آپ نشد، لطفا با فیلترشکن باز نمایید.',
      description3: '',
      tools: ['HTML', 'CSS', "react-reveal",'BootStrap', 'JavaScript', 'React'],
      links: { github: "https://github.com/omids0/", live: "https://omid-soheilnia-projects.herokuapp.com/" },
    }
  ],
};
